According to https://arxiv.org/html/2602.14487v3, you can flip coins to calculate pi! I read through the manuscript and didn't find any major problems with it.
A minor issue I see is that the limit on the sum for the expected value of $H_\tau/\tau$ isn't infinity, but k will in principal go to infinity.

Let's check it through simulation.

In [1]:
import numpy as np

#let's generate a suitable number of pseudo-random coin flips, with heads = 1, tails = -1
seed = 6213214
rng = np.random.default_rng(seed)
n_flips = 10_000_000
#generates n_flips number of PRNs
U = rng.random(n_flips)
#convert to heads and tails
flips = (np.ceil(2*U)*2-3).astype('int64')
#print(flips)

#now let's find the index locations at which the number of heads increases the number of tails for a given run.
#To do this, we calculate the cumulative sum of flips, and record the index of every point at which the cumulative sum
#increases above its previous maximum. The difference in the indices is the stopping time tau, and the number of heads is 
#half of the tau rounded up

cume = np.cumsum(flips)
#The number of runs in which the number of heads in sequential tosses is greater than the number of tails is just the max of the cumulative sum. 
n_runs = cume.max() if cume.max()>0 else 0 #it's possible to get zero runs of mostly heads
#array to record the indices
flip_indices = np.arange(n_flips)
run_indices = np.zeros(n_runs).astype('int')
#loop through the runs and record the indices where runs end
for i in range(n_runs):
    run_indices[i] =flip_indices[np.where(cume==i+1)][0]

#now we can use the run indices to find tau and H_tau
#for H_tau we just take the difference between successive array entries, and we need to include the first entry
if n_runs>0:
    tau = np.append(run_indices[0]+1,run_indices[1:]-(run_indices)[:-1])
    H_tau = np.ceil(tau/2)

#finally, we can calculate pi
print('pi is approximately {0:.5f}'.format(4*(H_tau/tau).mean()) )

pi is approximately 3.12296


In [ ]:
tau

array([16, 17, 18, 21, 22, 39])

In [73]:
indices

array([1, 1, 3, 6, 4, 5, 6, 7, 8, 9])

In [52]:
(cume==0)|np.zeros_like(cume)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.ones(n_flips)*False

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])